#!/bin/bash
echo "=== 피그마 디자인 체크리스트 ==="
echo ""
echo "📐 락커 배치관리 화면 (18개 화면):"
echo "🔗 메인 링크: https://www.figma.com/design/HNPe8VljEBb1cJasZHJekA/"
echo ""
echo "📊 락커 배정관리 화면 (3개 화면):"
echo "🔗 메인 링크: https://www.figma.com/design/BXwBrhkCCZTTnnNGUezcvw/"
echo ""
echo "=== 디자인 토큰 추출 우선순위 ==="
echo "1. 락커 색상 (사용가능, 사용중, 만료, 정비중)"
echo "2. 락커 크기 및 비율"
echo "3. 전체 레이아웃 구조"
echo "4. 버튼 및 모달 스타일"
echo "5. 타이포그래피 시스템"
echo ""
echo "📋 체크리스트 파일: project_context/design_checklist.md"